test

diff --git a/linux_run_git b/linux_run_git
--- a/linux_run_git
+++ b/linux_run_git
@@ -1,3 +1,11 @@
 #!/bin/sh
 #git checkout dev
+
+echo "拉取远程分支代码"
 git pull origin dev
+
+if [ $? -eq 0 ]; then
+    echo "[H] done!"
+else
+    echo "[H] failed!"
+fi
diff --git a/win_run_git b/win_run_git
--- a/win_run_git
+++ b/win_run_git
@@ -1,6 +1,19 @@
 #!/bin/sh
+echo "切换到dev分支"
 git checkout dev
+
+echo "commit"
 git add .
 git commit -m "test"
+
+echo "拉取远程分支"
 git pull origin dev
+
+echo "推送远程分支"
 git push origin dev
+
+if [ $? -eq 0 ]; then
+    echo "[H] done!"
+else
+    echo "[H] failed!"
+fi
